CREATE TABLE DEV.VENDEDOR(
    COD_VENDEDOR INT,
    NOME VARCHAR2(40),
    CPF VARCHAR2(11),
    SENHA VARCHAR2(128),
    MATRICULA VARCHAR2(20),
	USER_CREATED VARCHAR2(20),
	DATE_CREATED DATE,
	USER_MODIFIED VARCHAR2(20),
	DATE_MODIFIED DATE,
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (COD_VENDEDOR)
);

CREATE TABLE DEV.CLIENTE(
    COD_CLIENTE INT,
    NOME VARCHAR2(100),
    DOC_TYPE VARCHAR2(4),
    DOC_NUM VARCHAR2(14),
	USER_CREATED VARCHAR2(20),
	DATE_CREATED DATE,
	USER_MODIFIED VARCHAR2(20),
	DATE_MODIFIED DATE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE DEV.PEDIDO(
    COD_PEDIDO INT,
    VALOR_TOTAL NUMBER,
    COD_CLIENTE INT,
    COD_VENDEDOR INT,
	USER_CREATED VARCHAR2(20),
	DATE_CREATED DATE,
	USER_MODIFIED VARCHAR2(20),
	DATE_MODIFIED DATE,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (COD_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES DEV.CLIENTE (COD_CLIENTE),
    CONSTRAINT FK_PEDIDO_VENDEDOR FOREIGN KEY (COD_VENDEDOR) REFERENCES DEV.VENDEDOR (COD_VENDEDOR)
);

CREATE TABLE DEV.PRODUTO(
    COD_PRODUTO INT,
    NOME VARCHAR2(100),
    VALOR NUMBER,
    QUANTIDADE INTEGER,
	USER_CREATED VARCHAR2(20),
	DATE_CREATED DATE,
	USER_MODIFIED VARCHAR2(20),
	DATE_MODIFIED DATE,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO)
);

CREATE TABLE DEV.PEDIDO_PRODUTO(
    COD_PRODUTO INT,
    COD_PEDIDO INT,
    QUANTIDADE INT,
	USER_CREATED VARCHAR2(20),
	DATE_CREATED DATE,
	USER_MODIFIED VARCHAR2(20),
	DATE_MODIFIED DATE,
    CONSTRAINT FK_PP_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES DEV.PRODUTO(COD_PRODUTO),
    CONSTRAINT FK_PP_PEDIDO  FOREIGN KEY (COD_PEDIDO)  REFERENCES DEV.PEDIDO(COD_PEDIDO)
);