SELECT
    PEDIDO.COD_PEDIDO,
    PRODUTO.NOME PRODUTO,
    PP.QUANTIDADE,
    CLIENTE.NOME CLIENTE,
    TO_CHAR(PEDIDO.DATE_CREATED, 'DD/MM/YYYY'),
    PRODUTO.VALOR,
    TO_CHAR((PRODUTO.VALOR * PP.QUANTIDADE), '9,999,999,999.99'),
    VENDEDOR.NOME VENDEDOR
FROM
    DEV.PEDIDO PEDIDO
    JOIN DEV.CLIENTE CLIENTE
    ON CLIENTE.COD_CLIENTE = PEDIDO.COD_CLIENTE
    JOIN DEV.VENDEDOR VENDEDOR
    ON VENDEDOR.COD_VENDEDOR = PEDIDO.COD_VENDEDOR
    JOIN DEV.PEDIDO_PRODUTO PP
    ON PP.COD_PEDIDO = PEDIDO.COD_PEDIDO
    JOIN DEV.PRODUTO PRODUTO
    ON PRODUTO.COD_PRODUTO = PP.COD_PRODUTO
WHERE
	VENDEDOR.CPF = NVL(?, VENDEDOR.CPF)
	AND PRODUTO.COD_PRODUTO = NVL(?, PRODUTO.COD_PRODUTO)
	AND PEDIDO.COD_PEDIDO = NVL(?, PEDIDO.COD_PEDIDO)
	AND CLIENTE.NOME = NVL(?, CLIENTE.NOME)
	AND TRUNC(PEDIDO.DATE_CREATED) BETWEEN NVL(?, TRUNC(PEDIDO.DATE_CREATED)) AND NVL(?, TO_CHAR(SYSDATE - 3/24, 'DD/MON/YYYY'))
ORDER BY
	PEDIDO.DATE_CREATED DESC