/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.Comandos;
import Classes.*;
import Imagens.Imagem;
import javax.swing.JSpinner;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author mello
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Comandos comandos;
    Funcionario funcionario;
    String[] colunas = {"PEDIDO", "PRODUTO", "QUANTIDADE", "CLIENTE", "DATA DO PEDIDO", "VALOR", "VALOR TOTAL", "VENDEDOR"};
    /**
     * Creates new form TelaPrincipalVendedor
     * @param comandos
     * @param funcionario
     * @throws java.sql.SQLException
     */
    public TelaPrincipal(Comandos comandos, Funcionario funcionario) throws SQLException {
        this.comandos = comandos;
        this.funcionario = funcionario;
        this.setIconImage(new Imagem().getImage("icon.png"));
        initComponents();
        
        // seta o nome e a matricula do funcionario na tela
        lblFuncionario.setText(funcionario.getNome());
        lblMatricula.setText(funcionario.getMatricula());
        
        // se o funcionario nao for um gerente, desabilita o botao de cadastrar funcionario e pedidos e remove o campo 'vendedor' da tabela
        if (!funcionario.getCargo().equals("GERENTE")){
            btnCadastrarProdutos.setEnabled(false);
            btnCadastrarFuncionario.setEnabled(false);
            btnCadastrarCliente.setEnabled(false);
            
            colunas = removeIndexFromArray(colunas, "VENDEDOR");
            
        }
        
        // popula a tabela com o historico dos pedidos do funcionario
        if (!funcionario.getCargo().equals("GERENTE")){
            tablePedidos.setModel(comandos.getPedidosVendedor(funcionario.getCpf(), null, null, null, null, null, tablePedidos, colunas));
        } else {
            tablePedidos.setModel(comandos.getPedidosVendedor(null, null, null, null, null, null, tablePedidos, colunas));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuRelatorioVenda = new javax.swing.JPopupMenu();
        baixarRelatorio = new javax.swing.JMenuItem();
        panelGeral = new javax.swing.JPanel();
        lblFuncionarioStatic = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        lblMatriculaStatic = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnCadastrarFuncionario = new javax.swing.JButton();
        btnNovoPedido = new javax.swing.JButton();
        btnCadastrarProdutos = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        scrollPaneTablePedidos = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        lblHistoricoPedidos = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        baixarRelatorio.setText("Baixar relatorio de venda");
        baixarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baixarRelatorioActionPerformed(evt);
            }
        });
        menuRelatorioVenda.add(baixarRelatorio);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EST 1.0");
        setMinimumSize(new java.awt.Dimension(1421, 608));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelGeral.setMinimumSize(new java.awt.Dimension(858, 560));
        panelGeral.setPreferredSize(new java.awt.Dimension(858, 560));
        panelGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelGeralMouseReleased(evt);
            }
        });

        lblFuncionarioStatic.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblFuncionarioStatic.setText("Funcionário.:");

        lblFuncionario.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        lblMatriculaStatic.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblMatriculaStatic.setText("Matrícula.:");

        lblMatricula.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSair.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCadastrarFuncionario.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnCadastrarFuncionario.setText("Gerenciar funcionarios");
        btnCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncionarioActionPerformed(evt);
            }
        });

        btnNovoPedido.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnNovoPedido.setText("Pedidos");
        btnNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPedidoActionPerformed(evt);
            }
        });

        btnCadastrarProdutos.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnCadastrarProdutos.setText("Gerenciar produtos");
        btnCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutosActionPerformed(evt);
            }
        });

        btnCadastrarCliente.setText("Gerenciar clientes");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovoPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnNovoPedido)
                    .addComponent(btnCadastrarFuncionario)
                    .addComponent(btnCadastrarProdutos)
                    .addComponent(btnCadastrarCliente))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablePedidos.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUTO", "QUANTIDADE", "CLIENTE", "DATA DO PEDIDO", "VALOR", "VALOR TOTAL", "VENDEDOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPaneTablePedidos.setViewportView(tablePedidos);

        lblBuscar.setText("Número do pedido.:");

        lblHistoricoPedidos.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblHistoricoPedidos.setText("Histórico de pedidos");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblHistoricoPedidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addComponent(scrollPaneTablePedidos))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHistoricoPedidos)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTablePedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelGeralLayout = new javax.swing.GroupLayout(panelGeral);
        panelGeral.setLayout(panelGeralLayout);
        panelGeralLayout.setHorizontalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGeralLayout.createSequentialGroup()
                                .addComponent(lblMatriculaStatic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelGeralLayout.createSequentialGroup()
                                .addComponent(lblFuncionarioStatic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGeralLayout.setVerticalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFuncionarioStatic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblMatriculaStatic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelGeral);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // busca o pedido de acordo com o id do pedido
        String entrada = txtBuscar.getText();

        if (isNumber(entrada) || entrada.isEmpty()) {        
            try {
                if (!funcionario.getCargo().equals("GERENTE")){
                    tablePedidos.setModel(comandos.getPedidosVendedor(funcionario.getCpf(), null, entrada, null, null, null, tablePedidos, colunas));
                } else {
                    tablePedidos.setModel(comandos.getPedidosVendedor(null, null, entrada, null, null, null, tablePedidos, colunas));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex, null, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "O ID do pedido é inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // desloga da conta do funcionario
        int sair = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja sair?", "Sair", JOptionPane.OK_CANCEL_OPTION);
        
        if (sair == 0) {
            dispose();
            try {
                new TelaLogin(comandos).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionarioActionPerformed
        try {
            // abre tela para cadastro de funcionario
            new TelaVendedor(this, true, comandos).setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro.: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarFuncionarioActionPerformed

    private void btnNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPedidoActionPerformed
        try {
            // abre a tela para cadastro de um novo pedido
            new TelaPedido(this, rootPaneCheckingEnabled, comandos, funcionario).setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro.: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNovoPedidoActionPerformed

    private void btnCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutosActionPerformed
        try {
            //abre a tela para cadastro de produtos
            new TelaProdutos(this, true, comandos).setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro.: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarProdutosActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        try {
            //abre a tela para cadastro de cliente
            new TelaCliente(this, true, comandos).setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro.: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void baixarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baixarRelatorioActionPerformed
        // abre a tela de relatorios
        new TelaRelatorioVenda(this, true, comandos, funcionario).setVisible(true);
    }//GEN-LAST:event_baixarRelatorioActionPerformed

    private void panelGeralMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGeralMouseReleased
        if (evt.isPopupTrigger()) {
            menuRelatorioVenda.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_panelGeralMouseReleased
    
    private boolean isNumber(String string){
        // checa se a string eh um integer
        try {
            Integer.parseInt(string);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    
    private String[] removeIndexFromArray(String[] array, String element){
        // constroi um novo array sem um elemento passado pelo parametro
        String[] arrayApoio = new String[array.length - 1];
        
        for (int i = 0; i < array.length; i++){
            if (!array[i].toUpperCase().equals(element.toUpperCase())){
                arrayApoio[i] = array[i];
            }
        }
        
        return arrayApoio;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem baixarRelatorio;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarFuncionario;
    private javax.swing.JButton btnCadastrarProdutos;
    private javax.swing.JButton btnNovoPedido;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblFuncionarioStatic;
    private javax.swing.JLabel lblHistoricoPedidos;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblMatriculaStatic;
    private javax.swing.JPopupMenu menuRelatorioVenda;
    private javax.swing.JPanel panelGeral;
    private javax.swing.JScrollPane scrollPaneTablePedidos;
    private static javax.swing.JTable tablePedidos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
