/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.Comandos;
import Classes.*;
import Imagens.Imagem;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author mello
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Comandos comandos;
    Funcionario funcionario;
    String[] colunas = {"PEDIDO", "PRODUTO", "QUANTIDADE", "CLIENTE", "DATA DO PEDIDO", "VALOR", "VALOR TOTAL", "VENDEDOR"};
    /**
     * Creates new form TelaPrincipalVendedor
     * @param comandos
     * @param funcionario
     * @throws java.sql.SQLException
     */
    public TelaPrincipal(Comandos comandos, Funcionario funcionario) throws SQLException {
        this.comandos = comandos;
        this.funcionario = funcionario;
        this.setIconImage(new Imagem().getImage("icon.png"));
        initComponents();

        // seta o nome e a matricula do funcionario na tela
        lblFuncionario.setText(funcionario.getNome());
        lblMatricula.setText(funcionario.getMatricula());
        
        // se o funcionario nao for um gerente, desabilita o botao de cadastrar funcionario e pedidos e remove o campo 'vendedor' da tabela
        if (!funcionario.getCargo().equals("GERENTE")){
            btnCadastrarProdutos.setEnabled(false);
            btnCadastrarFuncionario.setEnabled(false);
            btnCadastrarCliente.setEnabled(false);
            
            colunas = removeIndexFromArray(colunas, "VENDEDOR");
            
        }
        
        // popula a tabela com o historico dos pedidos do funcionario
        if (!funcionario.getCargo().equals("GERENTE")){
            tablePedidos.setModel(comandos.getPedidosVendedor(funcionario.getCpf(), null, null, null, null, null, tablePedidos, colunas));
        } else {
            tablePedidos.setModel(comandos.getPedidosVendedor(null, null, null, null, null, null, tablePedidos, colunas));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneGeral = new javax.swing.JScrollPane();
        panelGeral = new javax.swing.JPanel();
        lblFuncionarioStatic = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        lblMatriculaStatic = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnNovoPedido = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        lblHistoricoPedidos = new javax.swing.JLabel();
        scrollPaneTablePedidos = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        btnCadastrarFuncionario = new javax.swing.JButton();
        btnCadastrarProdutos = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EST 1.0");
        setMinimumSize(new java.awt.Dimension(1421, 608));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        scrollPaneGeral.setMinimumSize(new java.awt.Dimension(858, 560));

        panelGeral.setMinimumSize(new java.awt.Dimension(858, 560));
        panelGeral.setPreferredSize(new java.awt.Dimension(858, 560));

        lblFuncionarioStatic.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblFuncionarioStatic.setText("Funcionário.:");

        lblFuncionario.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        lblMatriculaStatic.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblMatriculaStatic.setText("Matrícula.:");

        lblMatricula.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        btnSair.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnNovoPedido.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnNovoPedido.setText("Novo pedido");
        btnNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPedidoActionPerformed(evt);
            }
        });

        btnRelatorio.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnRelatorio.setText("Relatório de venda");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        lblHistoricoPedidos.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblHistoricoPedidos.setText("Histórico de pedidos");

        tablePedidos.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUTO", "QUANTIDADE", "CLIENTE", "DATA DO PEDIDO", "VALOR", "VALOR TOTAL", "VENDEDOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPaneTablePedidos.setViewportView(tablePedidos);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblBuscar.setText("Número do pedido.:");

        btnCadastrarFuncionario.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnCadastrarFuncionario.setText("Gerenciar funcionarios");
        btnCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncionarioActionPerformed(evt);
            }
        });

        btnCadastrarProdutos.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnCadastrarProdutos.setText("Cadastrar produtos");
        btnCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutosActionPerformed(evt);
            }
        });

        btnCadastrarCliente.setText("Gerenciar clientes");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        btnEstoque.setText("Estoque");
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGeralLayout = new javax.swing.GroupLayout(panelGeral);
        panelGeral.setLayout(panelGeralLayout);
        panelGeralLayout.setHorizontalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTablePedidos)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addComponent(lblHistoricoPedidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 586, Short.MAX_VALUE)
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addComponent(lblMatriculaStatic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeralLayout.createSequentialGroup()
                        .addComponent(lblFuncionarioStatic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addComponent(btnCadastrarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadastrarProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadastrarFuncionario)
                        .addGap(12, 12, 12)
                        .addComponent(btnRelatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNovoPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        panelGeralLayout.setVerticalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSair)
                        .addComponent(btnNovoPedido)
                        .addComponent(btnRelatorio)
                        .addComponent(btnCadastrarFuncionario)
                        .addComponent(btnCadastrarProdutos)
                        .addComponent(btnCadastrarCliente)
                        .addComponent(btnEstoque))
                    .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFuncionarioStatic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblMatriculaStatic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHistoricoPedidos)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTablePedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        scrollPaneGeral.setViewportView(panelGeral);

        getContentPane().add(scrollPaneGeral);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // busca o pedido de acordo com o id do pedido
        String entrada = txtBuscar.getText();

        if (isNumber(entrada) || entrada.isEmpty()) {        
            try {
                if (!funcionario.getCargo().equals("GERENTE")){
                    tablePedidos.setModel(comandos.getPedidosVendedor(funcionario.getCpf(), null, entrada, null, null, null, tablePedidos, colunas));
                } else {
                    tablePedidos.setModel(comandos.getPedidosVendedor(null, null, entrada, null, null, null, tablePedidos, colunas));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex, null, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "O ID do pedido é inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // desloga da conta do funcionario
        int sair = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja sair?", "Sair", JOptionPane.OK_CANCEL_OPTION);
        
        if (sair == 0) {
            dispose();
            try {
                new TelaLogin(comandos).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionarioActionPerformed
        try {
            // abre tela para cadastro de funcionario
            new TelaVendedor(this, true, comandos).setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro.: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarFuncionarioActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // abre a tela de relatorios
        new TelaRelatorioVenda(this, true, comandos, funcionario).setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPedidoActionPerformed
        // abre a tela para cadastro de um novo pedido
        new TelaCadastroPedido(this, true, comandos, funcionario).setVisible(true);
    }//GEN-LAST:event_btnNovoPedidoActionPerformed

    private void btnCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutosActionPerformed
        //abre a tela para cadastro de produtos
        new TelaCadastroProdutos(this, true, comandos).setVisible(true);
    }//GEN-LAST:event_btnCadastrarProdutosActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        try {
            //abre a tela para cadastro de cliente
            new TelaCliente(this, true, comandos).setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro.: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        // abre a tela para consulta e extração do estoque
        new TelaEstoque(this, rootPaneCheckingEnabled, comandos).setVisible(true);
    }//GEN-LAST:event_btnEstoqueActionPerformed
    
    private boolean isNumber(String string){
        // checa se a string eh um integer
        try {
            Integer.parseInt(string);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
    
    private String[] removeIndexFromArray(String[] array, String element){
        // constroi um novo array sem um elemento passado pelo parametro
        String[] arrayApoio = new String[array.length - 1];
        
        for (int i = 0; i < array.length; i++){
            if (!array[i].toUpperCase().equals(element.toUpperCase())){
                arrayApoio[i] = array[i];
            }
        }
        
        return arrayApoio;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarFuncionario;
    private javax.swing.JButton btnCadastrarProdutos;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnNovoPedido;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblFuncionarioStatic;
    private javax.swing.JLabel lblHistoricoPedidos;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblMatriculaStatic;
    private javax.swing.JPanel panelGeral;
    private javax.swing.JScrollPane scrollPaneGeral;
    private javax.swing.JScrollPane scrollPaneTablePedidos;
    private static javax.swing.JTable tablePedidos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
