/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Telas;

import Classes.SHA512;
import DAO.Comandos;
import Classes.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author mello
 */
public class TelaCadastro extends javax.swing.JDialog {
    Comandos comandos;
    private float[] green = new float[3];
    private boolean verSenha = false;
    
    /**
     * Creates new form TelaCadastroJDialog
     * @param parent
     * @param modal
     * @param comandos
     */
    public TelaCadastro(java.awt.Frame parent, boolean modal, Comandos comandos) {
        super(parent, modal);
        this.comandos = comandos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        cbCargo = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblCadastro = new javax.swing.JLabel();
        lblContSenha = new javax.swing.JLabel();
        lblSenhaTam = new javax.swing.JLabel();
        lblSenhaMaiuscula = new javax.swing.JLabel();
        lblSenhaMinuscula = new javax.swing.JLabel();
        lblSenhaNum = new javax.swing.JLabel();
        lblSenhaEspecial = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        btnVerSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar funcionário");
        setIconImage(null);
        setIconImages(null);
        setResizable(false);

        lblNome.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblNome.setText("Nome.:");

        lblSenha.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblSenha.setText("Senha.:");

        lblCargo.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblCargo.setText("Cargo.:");

        txtNome.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txtNome.setToolTipText("Nome completo e sem acentos");
        txtNome.setMaximumSize(new java.awt.Dimension(7, 20));
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        txtSenha.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSenhaKeyReleased(evt);
            }
        });

        cbCargo.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Gerente" }));
        cbCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbCargoKeyPressed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        btnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarKeyPressed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        btnLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLimparKeyPressed(evt);
            }
        });

        lblCadastro.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastro.setText("Cadastro de Funcionário");

        lblContSenha.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblContSenha.setText("A senha deve conter:");

        lblSenhaTam.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblSenhaTam.setForeground(new java.awt.Color(255, 0, 0));
        lblSenhaTam.setText("• Entre 8 e 20 dígitos");

        lblSenhaMaiuscula.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblSenhaMaiuscula.setForeground(new java.awt.Color(255, 0, 0));
        lblSenhaMaiuscula.setText("• Uma letra maiúscula");

        lblSenhaMinuscula.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblSenhaMinuscula.setForeground(new java.awt.Color(255, 0, 0));
        lblSenhaMinuscula.setText("• Uma letra minúscula");

        lblSenhaNum.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblSenhaNum.setForeground(new java.awt.Color(255, 0, 0));
        lblSenhaNum.setText("• Um número");

        lblSenhaEspecial.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblSenhaEspecial.setForeground(new java.awt.Color(255, 0, 0));
        lblSenhaEspecial.setText("• Um caractere especial");

        lblCPF.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblCPF.setText("CPF.:");

        txtCPF.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txtCPF.setActionCommand("<Not Set>");
        txtCPF.setMaximumSize(new java.awt.Dimension(7, 20));
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCPFKeyTyped(evt);
            }
        });

        btnVerSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ver_senha.png"))); // NOI18N
        btnVerSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCargo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(66, 66, 66)
                                            .addComponent(lblCPF))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(53, 53, 53)
                                            .addComponent(lblNome)))
                                    .addComponent(lblSenha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addComponent(btnVerSenha)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblContSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSenhaTam, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSenhaMaiuscula, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSenhaMinuscula, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSenhaEspecial, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSenhaNum, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblCadastro)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo)
                    .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSenha))
                    .addComponent(btnVerSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblContSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenhaTam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenhaMaiuscula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenhaMinuscula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenhaNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenhaEspecial)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnLimpar))
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtSenha.requestFocus();
        }

        validaTamanho(txtNome, 40);
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCPF.requestFocus();
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    private void txtSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyReleased
        String senha = String.valueOf(txtSenha.getPassword());
        Color.RGBtoHSB(25, 99, 40, green);

        if (senha.length() >= 8 && senha.length() <= 20) {
            lblSenhaTam.setForeground(Color.getHSBColor(green[0], green[1], green[2]));
        } else {
            lblSenhaTam.setForeground(Color.red);
        }

        if (senha.matches("^(?=.*[A-Z]).{1,}")) {
            lblSenhaMaiuscula.setForeground(Color.getHSBColor(green[0], green[1], green[2]));
        } else {
            lblSenhaMaiuscula.setForeground(Color.red);
        }

        if (senha.matches("^(?=.*[a-z]).{1,}")) {
            lblSenhaMinuscula.setForeground(Color.getHSBColor(green[0], green[1], green[2]));
        } else {
            lblSenhaMinuscula.setForeground(Color.red);
        }

        if (senha.matches("^(?=.*[0-9]).{1,}")) {
            lblSenhaNum.setForeground(Color.getHSBColor(green[0], green[1], green[2]));
        } else {
            lblSenhaNum.setForeground(Color.red);
        }

        if (senha.matches("^(?=.*[!@#$%^&*()]).{1,}")) {
            lblSenhaEspecial.setForeground(Color.getHSBColor(green[0], green[1], green[2]));
        } else {
            lblSenhaEspecial.setForeground(Color.red);
        }

    }//GEN-LAST:event_txtSenhaKeyReleased

    private void cbCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCargoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnCadastrar.requestFocus();
        }
    }//GEN-LAST:event_cbCargoKeyPressed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cadastrar();
        }
    }//GEN-LAST:event_btnCadastrarKeyPressed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLimparKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            limpar();
        }
    }//GEN-LAST:event_btnLimparKeyPressed

    private void txtCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cbCargo.requestFocus();
        }
    }//GEN-LAST:event_txtCPFKeyPressed

    private void txtCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyTyped
        validaTamanho(txtCPF, 14);
    }//GEN-LAST:event_txtCPFKeyTyped

    private void btnVerSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSenhaActionPerformed
        if (!verSenha) {
            txtSenha.setEchoChar('\u0000');
            verSenha = !verSenha;
        } else {
            txtSenha.setEchoChar('*');
            verSenha = !verSenha;
        }
    }//GEN-LAST:event_btnVerSenhaActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVerSenha;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblContSenha;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenhaEspecial;
    private javax.swing.JLabel lblSenhaMaiuscula;
    private javax.swing.JLabel lblSenhaMinuscula;
    private javax.swing.JLabel lblSenhaNum;
    private javax.swing.JLabel lblSenhaTam;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    private void validaTamanho(JTextField texto, int tamanho) {
        if (texto.getText().length() >= tamanho){
            texto.setText(texto.getText().substring(0, tamanho-1));
        }
    }

    private void cadastrar() {
        String nome = txtNome.getText().trim().toUpperCase();
        String senha = String.valueOf(txtSenha.getPassword());
        String cargo = String.valueOf(cbCargo.getSelectedItem()).trim().toUpperCase();
        String cpf = String.valueOf(txtCPF.getText()).trim().replace(".", "").replace("-", "");
        
        boolean nomeValido, senhaValida, cpfValido;
        
        nomeValido = validaNome(nome);
        senhaValida = validaSenha(senha);
        cpfValido = validaCpf(cpf);
        
        SHA512 hash = new SHA512();
        
        try {
            senha = hash.toHexStr(hash.obtainSHA(senha));
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if (nomeValido && senhaValida && cpfValido) {
            Funcionario funcionario = new Funcionario(nome, cpf, cargo, null, senha);
            
            try {
                comandos.insertFuncionario(funcionario);
                
                JOptionPane.showConfirmDialog(null, "FUNCIONARIO INCLUÍDO!", null, JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                
                limpar();
            } catch (SQLException ex) {
                if (ex.getErrorCode() == 20000) {
                    JOptionPane.showConfirmDialog(null, "FUNCIONÁRIO JÁ CADASTRADO!", null, JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                    limpar();
                } else {
                    JOptionPane.showConfirmDialog(null, ex.getMessage(), null, JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                    limpar();
                }
                
                
            }
        }
    }

    private void limpar() {
        txtNome.setText(null);
        txtSenha.setText(null);
        cbCargo.setSelectedIndex(0);
        txtCPF.setText(null);
        
        lblSenhaTam.setForeground(Color.red);
        lblSenhaMaiuscula.setForeground(Color.red);
        lblSenhaMinuscula.setForeground(Color.red);
        lblSenhaNum.setForeground(Color.red);
        lblSenhaEspecial.setForeground(Color.red);
    }

    private boolean validaNome(String nome) {
        if (nome.isEmpty()) {
            JOptionPane.showConfirmDialog(null, "O nome não pode ser nulo!", null, JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!nome.matches("^(?![\\s.]+$)[a-zA-Z\\s.]*$")){
            JOptionPane.showConfirmDialog(null, "Nome inválido.\nColoque o nome sem acentos e sem números", null, JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }

    private boolean validaSenha(String senha) {
        if (!senha.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%&*()]).{8,20}")) {
            JOptionPane.showConfirmDialog(null, "A senha não atende aos requisitos!", null, JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private boolean validaCpf(String cpf) {
        if (cpf.isEmpty()){
            JOptionPane.showConfirmDialog(null, "O CPF não pode ser nulo!", null, JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (!cpf.matches("([0-9]{3}[\\.]?[0-9]{3}[\\.]?[0-9]{3}[-]?[0-9]{2})")){
            JOptionPane.showConfirmDialog(null, "O CPF não tem um formato válido!", null, JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
}
