/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Telas;

import Classes.Produto;
import DAO.Comandos;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mello
 */
public class TelaProdutos extends javax.swing.JDialog {
    Comandos comandos;
    ArrayList<Produto> produtos;
    /**
     * Creates new form TelaProdutos
     * @param parent
     * @param modal
     * @param comandos
     */
    public TelaProdutos(java.awt.Frame parent, boolean modal, Comandos comandos) throws SQLException {
        super(parent, modal);
        initComponents();
        
        this.comandos = comandos;
        
        produtos = comandos.getProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBaixar = new javax.swing.JPopupMenu();
        baixarSaldoEstoque = new javax.swing.JMenuItem();
        scrollTable = new javax.swing.JScrollPane();
        tablePesquisa = new javax.swing.JTable();
        panelPesquisa = new javax.swing.JPanel();
        lblCodigoPesquisa = new javax.swing.JLabel();
        txtCodigoPesquisa = new javax.swing.JTextField();
        lblNomePesquisa = new javax.swing.JLabel();
        txtNomePesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        panelEditar = new javax.swing.JPanel();
        lblCodigoEditar = new javax.swing.JLabel();
        txtCodigoEditar = new javax.swing.JTextField();
        lblNomeEditar = new javax.swing.JLabel();
        txtNomeEditar = new javax.swing.JTextField();
        lblValorEditar = new javax.swing.JLabel();
        txtValorEditar = new javax.swing.JFormattedTextField();
        lblQuantidadeEditar = new javax.swing.JLabel();
        spinQuantidadeEditar = new javax.swing.JSpinner();
        lblDescricaoEditar = new javax.swing.JLabel();
        scrollDescricaoEditar = new javax.swing.JScrollPane();
        txtDescricaoEditar = new javax.swing.JTextPane();
        btnAtualizar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        lblQtdCaracteresEditar = new javax.swing.JLabel();

        baixarSaldoEstoque.setText("Baixar saldo do estoque");
        baixarSaldoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baixarSaldoEstoqueActionPerformed(evt);
            }
        });
        menuBaixar.add(baixarSaldoEstoque);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        tablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME", "VALOR", "QUANTIDADE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePesquisaMouseClicked(evt);
            }
        });
        scrollTable.setViewportView(tablePesquisa);

        panelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "PESQUISA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblCodigoPesquisa.setText("CÓDIGO.:");

        lblNomePesquisa.setText("NOME.:");

        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPesquisaLayout = new javax.swing.GroupLayout(panelPesquisa);
        panelPesquisa.setLayout(panelPesquisaLayout);
        panelPesquisaLayout.setHorizontalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPesquisaLayout.createSequentialGroup()
                        .addComponent(lblCodigoPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPesquisaLayout.createSequentialGroup()
                        .addComponent(lblNomePesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomePesquisa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisa)
                .addContainerGap())
        );
        panelPesquisaLayout.setVerticalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoPesquisa)
                    .addComponent(txtCodigoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePesquisa)
                    .addComponent(txtNomePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEditar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "EDITAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblCodigoEditar.setText("CÓDIGO.:");

        txtCodigoEditar.setPreferredSize(new java.awt.Dimension(86, 22));

        lblNomeEditar.setText("NOME.:");

        lblValorEditar.setText("VALOR.:");

        txtValorEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtValorEditar.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtValorEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorEditarKeyTyped(evt);
            }
        });

        lblQuantidadeEditar.setText("QUANTIDADE.:");

        spinQuantidadeEditar.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lblDescricaoEditar.setText("DESCRIÇÃO.:");

        txtDescricaoEditar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoEditarKeyReleased(evt);
            }
        });
        scrollDescricaoEditar.setViewportView(txtDescricaoEditar);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        lblQtdCaracteresEditar.setText("(/1000)");

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollDescricaoEditar)
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addComponent(lblNomeEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeEditar))
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addComponent(lblValorEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorEditar))
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addComponent(lblDescricaoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQtdCaracteresEditar))
                    .addGroup(panelEditarLayout.createSequentialGroup()
                        .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEditarLayout.createSequentialGroup()
                                .addComponent(lblCodigoEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEditarLayout.createSequentialGroup()
                                .addComponent(lblQuantidadeEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinQuantidadeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar)))
                .addContainerGap())
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoEditar)
                    .addComponent(txtCodigoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEditar)
                    .addComponent(txtNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorEditar)
                    .addComponent(txtValorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeEditar)
                    .addComponent(spinQuantidadeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricaoEditar)
                    .addComponent(lblQtdCaracteresEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDescricaoEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(btnIncluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablePesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePesquisaMouseClicked
        int row = tablePesquisa.rowAtPoint(evt.getPoint());

        String codigo = tablePesquisa.getValueAt(row, 0).toString();
        String nome = tablePesquisa.getValueAt(row, 1).toString();
        String valor = tablePesquisa.getValueAt(row, 2).toString();
        int quantidade = Integer.parseInt(tablePesquisa.getValueAt(row, 3).toString());

        txtCodigoEditar.setText(codigo);
        txtNomeEditar.setText(nome);
        txtValorEditar.setValue(Double.parseDouble(valor));
        
        SpinnerNumberModel modelo = (SpinnerNumberModel) spinQuantidadeEditar.getModel();
        modelo.setMinimum(quantidade);
        modelo.setValue(quantidade);
        spinQuantidadeEditar.setModel(modelo);
        
        for (Produto produto : produtos){
            String codigoAux = String.valueOf(produto.getCodigo());
            if (codigoAux.equals(codigo)) {
                String descricao = produto.getDescricao();
                
                txtDescricaoEditar.setText(descricao);
                
                try{
                    lblQtdCaracteresEditar.setText("(" + descricao.length() + "/1000)");
                } catch (NullPointerException ex) {
                    lblQtdCaracteresEditar.setText("(0/1000)");
                }
                break;
            }
        }
    }//GEN-LAST:event_tablePesquisaMouseClicked

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        String codigo = txtCodigoPesquisa.getText();
        String nome = txtNomePesquisa.getText();

        try {
            produtos = comandos.getProduto();
        } catch (SQLException ex) {
            Logger.getLogger(TelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pesquisarProdutos(codigo, nome);
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void txtValorEditarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorEditarKeyTyped
        char letra = evt.getKeyChar();
        if (((letra < '0') || (letra > '9')) && (letra != KeyEvent.VK_COMMA) && (letra != KeyEvent.VK_PERIOD) && (letra != KeyEvent.VK_BACK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtValorEditarKeyTyped

    private void txtDescricaoEditarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoEditarKeyReleased
        String descricao = txtDescricaoEditar.getText();
        lblQtdCaracteresEditar.setText("(" + descricao.length() + "/1000)");
        
        if (descricao.length() >= 1000) {
            descricao = descricao.substring(0, descricao.length()-1);
            txtDescricaoEditar.setText(descricao);
        }
    }//GEN-LAST:event_txtDescricaoEditarKeyReleased
    
    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        String nome = txtNomeEditar.getText();
        double valor = Double.parseDouble(txtValorEditar.getValue().toString());
        int quantidade = Integer.parseInt(spinQuantidadeEditar.getValue().toString());
        String descricao = txtDescricaoEditar.getText();
        
        Produto produto = new Produto(nome, quantidade, valor, descricao);
        
        try {
            comandos.insertProduto(produto);
            produtos = comandos.getProduto();
            btnPesquisa.doClick();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro.: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        int codigo = Integer.parseInt(txtCodigoEditar.getText());
        String nome = txtNomeEditar.getText();
        double valor = Double.parseDouble(txtValorEditar.getValue().toString());
        int quantidade = Integer.parseInt(spinQuantidadeEditar.getValue().toString());
        String descricao = txtDescricaoEditar.getText();
        
        Produto produto = new Produto(codigo, nome, quantidade, valor, descricao);
        
        try {
            comandos.updateProduto(produto);
            produtos = comandos.getProduto();
            btnPesquisa.doClick();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro.: " + ex, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if(evt.isPopupTrigger()){
            menuBaixar.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseReleased

    private void baixarSaldoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baixarSaldoEstoqueActionPerformed
        btnPesquisa.doClick();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyyMMdd_HHmm");
        String filename = "SALDO_ESTOQUE_EST_" + formatter.format(new Date()) + ".csv";
        
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Comma Separated Values (.csv)", "csv");
        chooser.addChoosableFileFilter(filtro);
        
        filename = chooser.getCurrentDirectory() + "\\" + filename;
        chooser.setSelectedFile(new File(filename));
        
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION){
            if (!chooser.getSelectedFile().isDirectory()){
                filename = chooser.getSelectedFile().getAbsolutePath() + ".csv";
            }
            
            try {
                 exportToCsv(filename);
                JOptionPane.showMessageDialog(null, "Relatório exportado para\n" + filename, null, JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Erro.: " + ex, null, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_baixarSaldoEstoqueActionPerformed
    
    private void exportToCsv(String path) throws IOException{
        DefaultTableModel modelo = getModel();
        
        try (FileWriter csv = new FileWriter(new File(path))){
            csv.write("CODIGO PRODUTO;PRODUTO;QUANTIDADE;VALOR\n");
            
            for (int i = 0; i < modelo.getRowCount(); i++){
                for (int j = 0; j < modelo.getColumnCount(); j++){
                    csv.write(modelo.getValueAt(i, j).toString() + ";");
                }
                csv.write("\n");
            }
        }
    }
    
    private DefaultTableModel getModel(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        for (Produto produto : produtos){
            modelo.addRow(new Object[] {
                produto.getCodigo(),
                produto.getNome(),
                produto.getQuantidade(),
                produto.getValor()
            });
        }
        
        return modelo;
    }
    
    private void pesquisarProdutos(String codigo, String nome){
        DefaultTableModel modelo = (DefaultTableModel) tablePesquisa.getModel();
        modelo.setRowCount(0);
        
        for (Produto produto : produtos){
            String codigoAux = String.valueOf(produto.getCodigo());
            String nomeAux = produto.getNome();
            
            if (!codigo.equals("")){
                if (codigoAux.startsWith(codigo)) modelo.addRow(new Object[]{produto.getCodigo(), produto.getNome(), produto.getValor(), produto.getQuantidade()});
            } else if (!nome.startsWith("")){
                if (nomeAux.startsWith(nome)) modelo.addRow(new Object[]{produto.getCodigo(), produto.getNome(), produto.getValor(), produto.getQuantidade()});
            } else {
                modelo.addRow(new Object[]{produto.getCodigo(), produto.getNome(), produto.getValor(), produto.getQuantidade()});
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem baixarSaldoEstoque;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JLabel lblCodigoEditar;
    private javax.swing.JLabel lblCodigoPesquisa;
    private javax.swing.JLabel lblDescricaoEditar;
    private javax.swing.JLabel lblNomeEditar;
    private javax.swing.JLabel lblNomePesquisa;
    private javax.swing.JLabel lblQtdCaracteresEditar;
    private javax.swing.JLabel lblQuantidadeEditar;
    private javax.swing.JLabel lblValorEditar;
    private javax.swing.JPopupMenu menuBaixar;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JPanel panelPesquisa;
    private javax.swing.JScrollPane scrollDescricaoEditar;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JSpinner spinQuantidadeEditar;
    private javax.swing.JTable tablePesquisa;
    private javax.swing.JTextField txtCodigoEditar;
    private javax.swing.JTextField txtCodigoPesquisa;
    private javax.swing.JTextPane txtDescricaoEditar;
    private javax.swing.JTextField txtNomeEditar;
    private javax.swing.JTextField txtNomePesquisa;
    private javax.swing.JFormattedTextField txtValorEditar;
    // End of variables declaration//GEN-END:variables
}
